version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: ./docker/db/DockerfileMongo
    ports:
      - 27017:27017

  application:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/proddb
      SPRING_DATA_MONGODB_HOST: mongo
    depends_on:
      - mongo
