version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: ./docker/db/DockerfileMongo
    ports:
      - 27017:27017

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/proddb
      SPRING_DATA_MONGODB_HOST: mongo
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend