spring:
  data:
    mongodb:
      port: 27017
      database: proddb

jwt:
  signing:
    key:
      secret: mySecret
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800
props:
  bannedWordsFilename: banned_words.txt
  replacingString: XXX