spring:
  data:
    mongodb:
      port: 27017
      database: proddb
      host: 192.168.99.100

jwt:
  signing:
    key:
      secret: mySecret
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800
props:
  bannedWordsFilename: banned_words.txt
  replacingString: XXX

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile
logging:
  file: log/app.log